version: '3.1'
services:
  db:
    image: mysql:5.7
    volumes:
      - ./createdb.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_HOST=
    ports:
      - "3306"

  app-be:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8080"
    ports:
      - "8080:8080"
    depends_on:
      - db